/**
 * English locale (default, D14).
 *
 * The `schemaDoc` is the full English translation of the base tool's Spanish
 * SCHEMA_DOC (same sections, same order, nothing shortened). The prompts are
 * faithful translations of the base Spanish prompts.
 */
import type { YattStrings } from './index.js';

export const en: YattStrings = {
  locale: 'en',

  schemaDoc: `# YATT test format (schemaVersion 1)

A test is a JSON file (or object) with this contract:

{
  "schemaVersion": 1,
  "name": "my-test",            // short name, no "/", "\\\\" nor ".."
  "url": "https://example.com", // optional initial URL
  "headless": false,
  "steps": [ ... ],             // list of steps (see below)
  "variables": [ ... ],         // optional
  "envs": ["dev", "prod"],      // optional: variable environments
  "dataset": { "columns": ["col"], "rows": [{ "col": "v" }] } // optional
}

## Steps

Each step:

{ "id": "optional uuid (generated automatically)", "action": "<action>", "selector": "...", "value": "...", "label": "...", "disabled": false }

Leaf actions (most used):
- goto             go to a URL              → value = url
- click            click an element         → selector
- dblclick         double click
- hover            hover the mouse
- type             type text                → selector + value
- clear            clear a field            → selector
- upload           upload a file            → selector + value (path)
- select_option    choose an option         → selector + value
- check            check a checkbox/radio   → selector
- press_key        press a key              → value (e.g. "Enter", "Tab")
- wait_visible     wait for element visible → selector
- scroll_to_element  scroll to the element  → selector
- wait             wait seconds             → value (number)
- screenshot       capture the screen       → optional selector
- assert_visible   verify it exists         → selector
- assert_hidden    verify it does not exist → selector
- assert_text      verify text              → selector + value (expected text)
- assert_value     verify value             → selector + value
- assert_attribute verify attribute         → selector + attribute (name) + value (expected)
- db_assert        verify against the app database    → sql (+ expect: "rows"|"empty"|"value" + value)
- db_wait          wait for data in the app database  → sql (+ optional value, timeout, interval)

Structure actions (containers with children):
- if        condition: the selector exists (or value with a variable) → children (yes) + elseChildren (no)
- repeat    repeat N times                → times (number) + children
- for_each  iterate a list                → list ("a,b,c" or "{{variable}}") + itemVar (variable name) + children
- run_flow  run a sub-flow                → flow (name of another saved test) + optional withVars (mapping)
- open_tab  open a tab                    → value (url)
- switch_tab switch to a tab              → value (index, 0-based)
- close_tab close a tab                   → optional value (index; without value closes the active one)
- capture_screenshot  save a reference image → value (base name) + optional fullPage
- assert_screenshot   compare with the baseline image → baseline (name) + tolerance (0-100) + optional fullPage

Rules:
- Steps run in order. A step with "disabled": true is skipped.
- "label" is a visible description (optional, generated by the app).
- Selectors: data-testid, id or short CSS; priority data-testid → id → unique CSS.
- Sub-flows (run_flow) must exist as saved tests; the runner looks them up in
  tests/ and detects cycles.

## Variables and environments

{
  "variables": [
    { "name": "user", "type": "text", "values": { "default": "demo", "dev": "demo", "prod": "admin" } }
  ],
  "envs": ["dev", "prod"]
}

- types: "text" | "number" | "option" | "file". "option" variables carry "options": ["a","b"].
- Any "value"/"selector"/"attribute" of a step supports {{variableName}} interpolation.
- A run picks one environment (default when not specified); per-run overrides win.

## Dataset (data-driven)

{
  "dataset": { "columns": ["user", "pass"], "rows": [ { "user": "a@x.com", "pass": "123" }, ... ] }
}
Rows are used as variable overrides (one run per row).

## Verification against the database

The db_assert and db_wait steps query the database of the app under test.
Configure the connection with the YATT_APP_DB environment variable or the
--app-db flag of the engine (SQLite path or "file:" / postgres:// URL; the
connection is read-only and responses are capped at 200 rows, although
totalRows counts them all).
{ "action": "db_assert", "sql": "SELECT status FROM orders WHERE id = {{orderId}}", "expect": "value", "value": "paid" }
{ "action": "db_wait", "sql": "SELECT status FROM jobs WHERE id = {{jobId}}", "value": "done", "timeout": 15, "interval": 0.5 }

- expect: "rows" (default; requires ≥1 row) | "empty" (requires 0 rows) | "value" (compares the first cell, stringified and trimmed, with value).
- db_wait repeats the query until it holds (value matches, or there are rows when no value is passed) or the timeout expires in seconds (default 10; interval in seconds, default 0.5, minimum 0.1).
- Read-only guard: any statement that does not start with SELECT, WITH, EXPLAIN or PRAGMA is rejected.

## Quick guide for AI agents

1. Use test_validate before saving: it returns errors or the normalized summary.
2. Prefer assert_* actions at the end of the test to verify results.
3. Use {{variable}} instead of fixed values when the data varies per environment.
4. After creating/editing, run with test_run and read the report (report_get or yatt://reports/<name>) to diagnose failures.
5. To explore a page use browser_open + browser_preview (the AI sees the screenshot) + browser_eval to inspect the DOM and pick robust selectors.
6. A flow that repeats (login, sign-ups, approvals) belongs in a saved test with variables, reused via run_flow + withVars; do not repeat it live cycle after cycle.
7. Sessions: save the logged-in state with session_save and reopen it with session in browser_open to switch users without logging in again.
8. Multiple users or data combinations: variables + dataset (one run per row) or overrides in test_run; do not duplicate tests.
9. Wait for conditions, not deadlines: wait_visible, an assert or db_wait (for data written in the background by another process) before moving on; fixed waits only as a last resort.
10. The strong proof of a flow is a db_assert against the database; do not leave the browser to check by hand.`,

  prompts: [
    {
      name: 'create-test',
      description: 'Guide to create a YATT test from scratch, run it and leave it green',
      text: `You are going to create a complete YATT test. Procedure:

1. Read the yatt://schema resource (or call the schema tool) to learn the exact format and the available actions.
2. If you need to explore the page under test: browser_open (url) → browser_preview (you can see the screenshot) → browser_eval to inspect the DOM and pick robust selectors (priority: data-testid → id → short unique CSS).
3. Build the test document (schemaVersion 1, steps with goto/click/type/assert_*… actions).
4. Validate it with test_validate; fix any errors it returns.
5. Save it with test_create and run it with test_run (headless, saves a report).
6. If there are failures, read the report (report_get or yatt://reports/<slug>.json), look at the failing step's screenshot with the live browser if needed, fix it with test_update and run again.
7. Finish only when the report comes back ok with no failures.

Rules: concrete and stable selectors; {{name}} variables for data that varies per environment; asserts at the end to verify results; never invent URLs or data that did not come from the user.`,
    },
    {
      name: 'diagnose-report',
      description: 'Analyzes a run report, finds the root cause of the failures and proposes fixes',
      text: `You are going to diagnose a YATT run report. Procedure:

1. Ask for the name of the report to diagnose, or list them with report_list.
2. Read the report with report_get (or the yatt://reports/<name> resource). Each failed step has status "fail", error and ms; steps can also be "skipped" or "stopped".
3. Identify the root cause of the first failure: broken selector, insufficient wait (add wait_visible before it), wrong variable value, down URL, or a different page flow.
4. Verify the hypothesis with the live browser: browser_open → browser_preview → browser_eval (does the selector exist? does the text differ?).
5. Propose the concrete change to the step (new selector or value) and, if the user approves, apply it with test_update.

Response format: root cause, evidence (from the report and the browser), and the exact proposed fix.`,
    },
    {
      name: 'explore-page',
      description: 'Explores a page with the live browser (visible screenshots) and produces a map of the UI',
      text: `You are going to explore a web page with the YATT controlled browser. Procedure:

1. browser_open with the URL (headless by default).
2. browser_preview to see the page; repeat browser_scroll (positive dy moves down) + browser_preview until you have covered it.
3. Use browser_eval to extract useful information: visible text, links (hrefs), inputs (names/ids/placeholders), buttons, section titles. Example expressions:
   - [...document.querySelectorAll("a")].map(a => [a.textContent.trim(), a.href])
   - [...document.querySelectorAll("input")].map(i => ({type: i.type, name: i.name, id: i.id, ph: i.placeholder}))
   - document.title + location.href
4. If there is interaction (login, menus), run steps with browser_run_step and verify with browser_condition/browser_preview.
5. Deliver a structured map: sections, interactive elements with recommended robust selectors, and possible test flows.

Rule: do not modify real data; if you need to type into forms, use test values and say so.`,
    },
    {
      name: 'export-spec',
      description: 'Exports a YATT test to Playwright code (TypeScript spec)',
      text: `You are going to export a YATT test to Playwright code. Procedure:

1. Ask for the test name or list them with test_list.
2. Call test_export_playwright(name, write: true) to generate it (it also returns the content).
3. Review the generated spec: check that the requirements (npm i -D @playwright/test) are documented and that the sub-flows are embedded.
4. Deliver the path of the exports/<name>.spec.ts file and a summary of what the spec covers.`,
    },
    {
      name: 'flow-battery',
      description:
        'Guide to turn repeated flows into a reusable battery: login with variables, saved sessions, sub-flows and data-driven runs',
      text: `You are going to turn the flows you repeat live today (logins, sign-ups, approvals, full cycles) into a battery of reusable tests. Goal: record once, reuse by changing only the data.

Golden rule: if you have already repeated a flow twice live, the third time it goes into a saved test. Do not keep clicking the same thing.

Procedure:

1. Identify the repeated flows and what varies in each cycle: users/roles, credentials, form data.
2. Record the login ONCE as a test with {{user}} and {{pass}} variables (no fixed credentials). Pick robust selectors with browser_open + browser_preview + browser_eval (data-testid → id → short unique CSS), build the JSON, validate it with test_validate, save it with test_create and leave it green with test_run.
3. Save each user/role session: with the browser logged in, session_save with a clear name (e.g. "admin", "operator"). In the next cycles open with browser_open + session instead of logging in again: switching roles is instant and destroys nothing.
4. Split long flows into saved sub-flows (one test per leg: login, create record, attach, advance) and compose them with run_flow + withVars to inject each cycle's data.
5. What varies goes into variables, not duplicated tests: test_run with overrides for a different run, or test_run_dataset for one run per row (e.g. one per user).
6. Wait for conditions, not deadlines: wait_visible (or an assert) before moving on; fixed waits only as a last resort and kept short.
7. Run the full battery with test_run (headless) and diagnose failures with report_get + the live browser.

Deliverable: green saved tests, sessions per user, and a summary of what each one covers. Next time the same check comes up, run test_run: do not redo the flows live.`,
    },
  ],

  resources: {
    schema: 'Documentation of the YATT test format (schema v1)',
    test: 'JSON content of a saved test',
    report: 'JSON report of a run (steps with status/error/ms)',
  },

  tools: {
    ping: 'Checks that the MCP server and the engine (sidecar) respond.',
    schema:
      'Complete documentation of the YATT test format (schema v1): fields, actions, variables, dataset and usage guide. Read it before creating tests.',
    baselineList: 'Lists the saved reference images (visual asserts).',
    baselineGet: 'Returns a reference image as PNG (for visual comparison).',
    testList: 'Lists the tests saved in the YATT library (names).',
    testGet: 'Returns a saved test as a full JSON object (steps, variables, environments, dataset).',
    testCreate:
      'Creates a new test. Accepts the content as a JSON string or as an object. Validates the schema (schemaVersion, steps, actions). Fails if the name already exists unless overwrite: true.',
    testUpdate:
      'Replaces the full content of an existing test (same validation as test_create).',
    testDelete: 'Deletes a test from the library (database and tests/<name>.yatt.json file).',
    testRename: 'Renames a test in the library (updates the DB and the mirror file).',
    testDuplicate: 'Duplicates an existing test under a new name (default "<name> (copy)").',
    testValidate:
      'Validates test content (JSON string or object) without saving it. Returns {ok: true, doc: summary} or {ok: false, error}. Useful before test_create/test_update.',
    testExport:
      'Generates the code of a saved test as a TypeScript spec (.spec.ts), in Playwright (@playwright/test) or Jest (jest-environment-playwright) format, with sub-flows embedded as functions. Returns the content; with write: true it saves the file into exports/<name>.spec.ts like the app.',
    reportList: 'Lists the saved run reports (names <slug>.json and <slug>.html).',
    reportGet:
      "Returns the content of a report (parseable JSON). To diagnose failures, the report has steps[] with status ok/fail, error and ms.",
    reportDelete: 'Deletes a saved report (DB + file under reports/).',
    dbQuery:
      'Executes a read-only query (SELECT/WITH/EXPLAIN/PRAGMA) against the app-under-test database. Pass the connection in `db` (SQLite path or "file:" / postgres:// URL); otherwise the engine-side YATT_APP_DB/--app-db configuration applies. Returns {columns, rows, totalRows}; rows are capped at 200.',
    testRun:
      'Runs a saved test headless (Chromium engine by default) and saves a report in the library. Parameters: variable environment, per-run overrides, per-step timeout. Returns the summary with the steps and the report name.',
    testRunDataset:
      'Data-driven: runs a test once per row of overrides and returns each row result plus totals. No report is saved.',
    browserOpen:
      'Open (or reopen) the controlled browser. headless=true by default; visible only when you need to point by hand.',
    browserClose: 'Closes the controlled browser (clears the browser session).',
    browserStatus:
      'State of the controlled browser: open/closed, engine, URL and interaction.',
    browserPreview:
      'Captures the current viewport as a PNG image (the AI sees the page) + url, title, scroll and dimensions. It is the main visual inspection tool.',
    browserEval:
      'Executes arbitrary JavaScript in the current page and returns the value (useful to inspect the DOM, read texts, count elements, try selectors).',
    browserRunStep:
      "Runs a YATT (leaf) step in the current page: click, type, hover, assert_*, goto, wait_visible, etc. Returns ok/error, duration and, on failure, an evidence screenshot. With `vars` it interpolates {{name}} into the step before running it. Structure steps (if/repeat/for_each/run_flow) run with test_run, not here.",
    browserCondition:
      'Checks whether an element exists in the page (or whether a variable condition holds); waits for the condition with optional polling (timeoutMs > 0 repeats the check until true or the timeout expires). Returns {value, elapsedMs}.',
    browserScroll:
      'Scrolls the page vertically (dy in pixels, positive moves down) and returns the updated preview.',
    browserClickAt:
      'Click at viewport coordinates (x, y in CSS pixels); returns the resolved selector of the clicked element (data-testid → id → CSS path) plus the updated preview. Prefer browser_run_step with a selector for reproducible steps.',
    tabOpen: 'Opens a new tab (optionally with a URL) and returns the tab list.',
    tabList: 'Lists the open tabs: index, active, title and URL.',
    tabSwitch: 'Switches to the tab with the given index (0-based).',
    tabClose: 'Closes a tab (by index; without an index closes the active one).',
    sessionSave:
      'Saves the current session state (cookies/localStorage) under a name, for tests with prior authentication.',
    sessionList: 'Lists the saved sessions.',
    sessionDelete: 'Deletes a saved session.',
  },

  args: {
    testName: 'Name of the saved test',
    nameToUpdate: 'Name of the test to replace',
    newName: 'New name',
    content: 'Test content: JSON string or object',
    overwrite: 'Overwrite if it already exists (default false)',
    suggestedName: 'Suggested name (optional)',
    format: 'Format of the generated spec (default "playwright")',
    write: 'Write the file into exports/ (default false)',
    reportName: 'Report name (see report_list, e.g. "my-test-YATT-20260902-101500.json")',
    sql: 'Read-only SQL query (SELECT, WITH, EXPLAIN or PRAGMA)',
    db: 'Connection: SQLite path or "file:" / postgres:// URL (overrides the global configuration)',
    runName: 'Name of the saved test',
    env: 'Variable environment (default "default")',
    overrides: 'Variable values that win over the environment',
    stepTimeoutMs: 'Timeout per step in ms (default 40000)',
    browser: 'Engine (default chromium)',
    url: 'Overrides the initial URL',
    saveReport: 'Save report in the library (default true)',
    rows: 'List of rows; one run per row (values = variable overrides)',
    openUrl: 'Initial URL (default about:blank)',
    headless: 'Headless mode (default true)',
    viewport: 'Viewport size (default 1280×800)',
    session:
      'Name of a saved session (cookies/localStorage). With sessions.persist:false the state is restored inline from memory',
    expression: 'JS expression (evaluated with the returned result)',
    runStepTimeoutMs: 'Timeout in ms (default 40000)',
    vars:
      'Variables to interpolate {{name}} into the step (e.g. { "email": "a@b.com" })',
    conditionSelector: 'Selector of the element to check',
    conditionValue: 'Alternative: variable condition (e.g. {{status}} == ok)',
    conditionTimeoutMs:
      'If > 0, polls until the condition is true or the timeout expires (default 0 = a single check)',
    intervalMs: 'Interval between checks in ms (default 300)',
    scrollDy: 'Pixels to scroll',
    clickX: 'X coordinate (CSS pixels)',
    clickY: 'Y coordinate (CSS pixels)',
    tabIndex: 'Tab index (see tab_list)',
    tabUrl: 'Initial URL of the new tab',
    sessionName: 'Session name',
  },

  messages: {
    testDoesNotExist: (name) => `test "${name}" does not exist`,
    testAlreadyExists: (name) => `test "${name}" already exists (use test_update or overwrite: true)`,
    testMissingCreate: (name) => `test "${name}" does not exist (use test_create)`,
    testNameTaken: (name) => `a test named "${name}" already exists`,
    reportMissingGet: (name) => `report "${name}" does not exist (use report_list)`,
    reportMissingDelete: (name) => `report "${name}" does not exist`,
    baselineMissing: (name) => `baseline image "${name}" does not exist`,
    subFlowMissing: (name) => `the sub-flow "${name}" does not exist in the library`,
    datasetSummary: (rows, columns) => `${rows} rows × ${columns} columns`,
    duplicateSuffix: '(copy)',
    dbReadOnly: () => 'db: read-only (SELECT/WITH/EXPLAIN/PRAGMA)',
    dbEngineRequired:
      'app database query requires the engine, not available in this server configuration',
    dbQueryTimeout: (timeoutMs) => `db: query timed out after ${timeoutMs} ms`,
    runTestMissing: (name) => `test "${name}" is not saved (create it with test_create first)`,
    runFailedNoReport: (tail) => `the run failed without a report: ${tail}`,
    engineRequired:
      'this tool requires the engine, which is not available in this server configuration (engine.enabled: false)',
    stepMustHaveAction: 'step must be an object with an action',
  },
};
